#ifndef __HCOLORS__
#define __HCOLORS__

enum HCOLORS {
    VGA_COLOR_BLACK = 0,
    VGA_COLOR_BLUE = 1,
    VGA_COLOR_GREEN = 2,
    VGA_COLOR_CYAN = 3,
    VGA_COLOR_RED = 4,
    VGA_COLOR_PURPLE = 5,
    VGA_COLOR_BROWN = 6,
    VGA_COLOR_GRAY = 7,
    VGA_COLOR_DARKGRAY = 8,
    VGA_COLOR_LIGHTBLUE = 9,
    VGA_COLOR_LIGHTGREEN = 10,
    VGA_COLOR_LIGHTCYAN = 11,
    VGA_COLOR_LIGHTRED = 12,
    VGA_COLOR_LIGHTPURPLE = 13,
    VGA_COLOR_YELLOW = 14,
    VGA_COLOR_WHITE = 15,
};

unsigned char H_GETCOLOR(unsigned char fg, unsigned char bg);

#endif
